# Generated by Django 5.2.3 on 2025-07-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs", "0006_alter_docentry_doc"),
    ]

    operations = [
        migrations.AddField(
            model_name="docentry",
            name="last_modified_by",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
