# Generated by Django 5.2.3 on 2025-06-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Docs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="docentry",
            name="name",
            field=models.CharField(default="New Doc", max_length=50),
            preserve_default=False,
        ),
    ]
