# Generated by Django 5.2.3 on 2025-06-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Docs", "0002_docentry_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="docentry",
            name="publicAccess",
            field=models.BooleanField(default=False),
        ),
    ]
