# Generated by Django 5.2.3 on 2025-06-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("docs", "0003_docentry_publicaccess"),
    ]

    operations = [
        migrations.RenameField(
            model_name="docentry",
            old_name="publicAccess",
            new_name="public_access",
        ),
    ]
