# Generated by Django 5.2.3 on 2025-07-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs", "0004_rename_publicaccess_docentry_public_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="docentry",
            name="uid",
            field=models.CharField(default="ABCTEST5", max_length=20),
            preserve_default=False,
        ),
    ]
