# Generated by Django 5.2.3 on 2025-07-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Docs", "0005_docentry_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docentry",
            name="doc",
            field=models.CharField(max_length=20),
        ),
    ]
